pragma Ada_2022;
--  =========================================================================
--  Hybrid_App_Ada - Root Package for Version Hierarchy
--  =========================================================================
--  Copyright (c) 2025 Michael Gardner, A Bit of Help, Inc.
--  SPDX-License-Identifier: BSD-3-Clause
--
--  Purpose:
--    Root package providing namespace for application-level child packages.
--    Currently serves as parent for Hybrid_App_Ada.Version.
--
--  Design Notes:
--    - Pure package (no state, no elaboration code)
--    - Exists solely to enable child package hierarchy
--    - Version child package is auto-generated by release scripts
--  =========================================================================

package Hybrid_App_Ada is
   pragma Pure;
end Hybrid_App_Ada;
